const mongoose = require('mongoose');

/* This code defines a Mongoose schema for a product with three fields: `_id` (a unique identifier
generated by Mongoose), `name` (a required string), and `price` (a required number). The schema is
then exported as a Mongoose model named `Product`. */

const productSchema = mongoose.Schema({
	_id: mongoose.Schema.Types.ObjectId,
	name: { type: String, required: true },
	price: { type: Number, required: true }
});

module.exports = mongoose.model('Product', productSchema);
